# NVIDIA & Wayland Support
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# Hardware Acceleration & Fixes
env = NVD_BACKEND,direct
env = ELECTRON_OZONE_PLATFORM_HINT,auto

# Aquamarine Fixes
# env = AQ_NO_ATOMIC,1
# env = AQ_NO_MODIFIERS,1

# idk
env = WLR_NO_HARDWARE_CURSOR,1
env = WLR_RENDERER_ALLOW_SOFTWARE,1

cursor {
	no_hardware_cursors = true
	enable_hyprcursor = true
}

# Keyboard layout
input {
	kb_layout = us,th
	kb_options = grp:win_space_toggle
}

# Monitor Configuration
# monitor = name, resolution, position, scale, transform

monitor = DP-3, 1920x1080@144, 0x0, 1
monitor = DP-2, 3440x1440@240, 1920x0, 1
monitor = HDMI-A-1, 1920x1080@144, 5360x0, 1, transform, 3

# Basic Keybinds
$mainMod = SUPER

bind = $mainMod, Q, exec, kitty
bind = $mainMod, R, exec, rofi -show drun -show-icons
bind = $mainMod, M, exit,
bind = $mainMod, C, killactive,
bind = $mainMod, V, togglefloating,

exec-once = waybar
