# Source from other files
source = ~/.config/hypr/themes/mocha.conf

general {
  gaps_in = 5
    gaps_out = 10
    border_size =2
    col.active_border = $active-border
    col.inactive_border = $inactive-border
    layout = dwindle
}

# NVIDIA & Wayland Support
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# Hardware Acceleration & Fixes
env = NVD_BACKEND,direct
env = ELECTRON_OZONE_PLATFORM_HINT,auto

# Aquamarine Fixes
# env = AQ_NO_ATOMIC,1
# env = AQ_NO_MODIFIERS,1

# idk
env = WLR_NO_HARDWARE_CURSOR,1
env = WLR_RENDERER_ALLOW_SOFTWARE,1

cursor {
  no_hardware_cursors = true
    enable_hyprcursor = true
}

# Keyboard layout
input {
  kb_layout = us,th
    kb_options = grp:win_space_toggle
}

# Cursor
input {
# Sensitivity: -1.0 to 1.0
  sensitivity = 0.1
  # Accel profiles: flat, adaptive
    accel_profile = flat
}

# Decoration

decoration {
  rounding = 10

    blur {
      enabled = true
        size = 6
        passes = 3
        new_optimizations = true
        ignore_opacity = true
        xray = true
    }
}
# Steam games
windowrule {
  name = steam_games
  match:class = ^(steam_app.*)$
  float = on
  fullscreen = on
  border_size = 0
}

# Kitty windowrule
windowrule {
  name = kitty_style
    match:class = ^(kitty)$
    opacity = 0.9 0.8
}

# Awakened PoE Trade window rules
windowrule {
  name = APT
  match:class = awakened-poe-trade
  float = on
  no_blur = true
  no_shadow = true
  border_size = 0
}

# Rofi Layer Rules
layerrule {
  name = rofi_layer
    match:namespace = ^(rofi)$
    blur = on
    ignore_alpha = on
}

# Dunst Layer Rules
layerrule {
  name = dunst_blur
    match:namespace = ^(notifications)$
    blur = on
    ignore_alpha = on
}

## Workspaces Binding
# Left
workspace = 1, monitor:DP-3, default:true, persistent:true
workspace = 2, monitor:DP-3, persistent:true

# Center 
workspace = 3, monitor:DP-2, default:true, persistent:true
workspace = 4, monitor:DP-2, persistent:true
workspace = 5, monitor:DP-2, persistent:true

# Right
workspace = 6, monitor:HDMI-A-1, default:true, persistent:true
workspace = 7, monitor:HDMI-A-1

# Monitor Configuration
# monitor = name, resolution, position, scale, transform

monitor = DP-3, 1920x1080@144, 0x0, 1
monitor = DP-2, 3440x1440@240, 1920x0, 1
monitor = HDMI-A-1, 1920x1080@144, 5360x0, 1, transform, 3

# Basic Keybinds
$mainMod = SUPER

bind = $mainMod, Q, exec, kitty
bind = $mainMod, R, exec, rofi -show drun -show-icons
bind = $mainMod, M, exit,
bind = $mainMod, C, killactive,
bind = $mainMod, V, togglefloating,
bind = $mainMod SHIFT, S, exec, hyprcap shot region -z -c -n
bind = $mainMod, L, exec, hyprlock
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, togglefloating

# Workpsaces Keybinds
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2

exec-once = waybar -c ~/.config/waybar/config
exec-once = waybar -c ~/.config/waybar/config_vertical.jsonc
exec-once = hyprpaper
