preload = /home/torumon/.config/hypr/wallpapers/wall_left_1.jpeg
preload = /home/torumon/.config/hypr/wallpapers/wall_ultrascreen.jpeg
preload = /home/torumon/.config/hypr/wallpapers/wall_vertical_cat_wave.jpeg

wallpaper {
	monitor = DP-3
	path = /home/torumon/.config/hypr/wallpapers/wall_left_1.jpeg
}

wallpaper {
	monitor = DP-2
	path = /home/torumon/.config/hypr/wallpapers/wall_ultrascreen.jpeg
}

wallpaper {
	monitor = HDMI-A-1
	path = /home/torumon/.config/hypr/wallpapers/wall_vertical_cat_wave.jpeg
}

splash = false
