# Master Color
# HEX color code can be also used here

$main-bg = rgb(1a1b26)
$main-fg = rgb(c0caf5)
$accent = rgb(7aa2f7)
$error = rgb(f7768e)
$border-active = rgba(7aa2f7ee) rgba(bb9af7ee) 45deg
$border-inactive = rgba(565f89aa)
