# Catppuccin Mocha Palette (Master)
$base = rgb(1e1e2e)
$text = rgb(cdd6f4)
$lavender = rgb(b4befe)
$mauve = rgb(cba6f7)
$sapphire = rgb(74c7ec)
$blue = rgb(89b4fa)
$red = rgb(f38ba8)
$maroon = rgb(eba0ac)

# Functional Assignments

$active-border = rgba(cba6f7ee) rgba(89b4faee) 45deg
$inactive-border = rgba(585b70aa)
