include theme.conf

# Fonts
font_family		JetBrainsMono Nerd Font
bold_font		auto
italic_font		auto
bold_italic_font	auto
font_size		12.0

# Window Layout
window_padding_width	15
confirm_os_window_close	0

# Transparency
background_opacity	0.8
background_blur		1

# Perfomance
repaint_delay		2
input_delay		0
sync_to_monitor	no

# Cursor
cursor_shape		beam
cursor_vi_mode_bold	yes

# Scrollback
scrollback_lines	2000

# Map Ctrl + - to send a custom sequence
map ctrl+minus send_text all \x1f

# Map Alt + - to send what Zsh expects
map alt+minus send_text all \e-
